//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageColor {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.FileUpload FileUpload1;
		
		protected System.Web.UI.WebControls.Button btnUpload;
		
		protected System.Web.UI.WebControls.Button btnInvert;
		
		protected System.Web.UI.WebControls.Image Img;
	}
}
